### ISSUE TITLE
no data/data.h5 file

### ISSUE THREAD

**Issue by yunlongdong** [leftthomas/ImageDeblurring#13]
In data_utils.py, code  `with h5py.File('data/data.h5', 'r') as f:`, 
there is no data.h5 in data/.

**Comment by leftthomas** [comment]
@yunlongdong do you really conscientious read my code? In data.utils.py, you could see the main function, so you just type `python data.utils.py`, then it will generate data.h5.

**Comment by TrinhQuocNguyen** [comment]
One more thing is that: converting float to int in data.utils.py file
```
    # slice image into full and blur images
    image_full = image.crop((0, 0, int(image.size[0] / 2), image.size[1]))
    # Note the full image in left, the blur image in right
    image_blur = image.crop((int(image.size[0] / 2), 0, image.size[0], image.size[1]))
```
