### ISSUE TITLE
FileNotFoundError: No such file or directory: 'result/interim/1_31.png'

### ISSUE THREAD

**Issue by Imagicguy** [leftthomas/ImageDeblurring#18]
First of all ,thanks for your project !When I tried to train the model,I found there are some new folders needed in the project ,such as 'result','weight'.Do I need to create those folders  ? I tried to create those folder under '\ImageDeblurring-master',but there is still a **FileNotFoundError** when comes to 30 batchs

**Comment by leftthomas** [comment]
@Imagicguy https://github.com/leftthomas/ImageDeblurring/blob/82b35592c658e361992f6174d916dca4f72fc18a/main.py#L38
you should creat the `interim` dir on `result` dir by yourself
