### ISSUE TITLE
Why does the output image turn into zero after training 20 epochs?

### ISSUE THREAD

**Issue by machengcheng2016** [leftthomas/ImageDeblurring#22]
Hello! Nice work of image deblurring! 
I kept all hyper-parameters that you set, but just changed the epoch number from 10 to 200, only to see more intermediate results. However, after training 20 epochs, the intermediate results turn into zero, which are like(from left to right: groundtruth, blurry input, output image):
![20_271_1](https://user-images.githubusercontent.com/22851860/41700505-1e6a2d12-755b-11e8-97b4-7a7719a12b78.png)
![20_301_2](https://user-images.githubusercontent.com/22851860/41700506-1ea1521a-755b-11e8-8f58-bd42d0ddb463.png)
I wonder why the training process goes wrong when I keep training. Thanks for you attention!

**Comment by leftthomas** [comment]
@machengcheng2016 #16
