### ISSUE TITLE
Why the test results are still quite blurred?

### ISSUE THREAD

**Issue by kwang3939** [leftthomas/ImageDeblurring#23]
I ran the code with the channel rate set to 16 without changing other parts.
But the output of the test images are still very blurred and not as good as the paper shows.
Is there any way to improve it?

**Comment by leftthomas** [comment]
@WangKewei1998 you should change the channel rate as the paper said and you need a powerful GPU to run the code, because it requires many memory.

**Comment by kwang3939** [comment]
@leftthomas I tried 64 as the channel rate. But it has the similar problem as other people mentioned before. The generated images of the test set are all green or blue. So I tried what they suggested and changed the channel rate to 16.

**Comment by leftthomas** [comment]
@WangKewei1998 maybe the problem is the loss function, I used different loss as the paper said

**Comment by kwang3939** [comment]
@leftthomas So, how is your result?
