### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wenzhifang** [leftthomas/ImageDeblurring#26]
OSError: Unable to open file (unable to open file: name = 'data/data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
had i missed  something?

**Comment by leftthomas** [comment]
@Mrfangfang run `data_utils.py` first.

**Comment by wenzhifang** [comment]
> @Mrfangfang run `data_utils.py` first.

thank you~ solved
