### ISSUE TITLE
训练的时候

### ISSUE THREAD

**Issue by x3393467** [leftthomas/ImageDeblurring#28]
训练的时候一直OOM，，     可以请问你一下你训练使用的配置吗？

**Comment by leftthomas** [comment]
@x3393467 change `channel_rate ` to 16, and use small `batch_size`, I trained on TITAN X GPU.

**Comment by Alukassh** [comment]
> @x3393467 change `channel_rate ` to 16, and use small `batch_size`, I trained on TITAN X GPU.

i had try this, the results are almost the same as the blurred ones, what's the problem?

**Comment by leftthomas** [comment]
@Alukassh add more images and use better GPU, if we decrease  `channel_rate`, it will be insufficient
