### ISSUE TITLE
Why the result is not good enough?

### ISSUE THREAD

**Issue by Alukassh** [leftthomas/ImageDeblurring#29]
When i change the channel-rate to be 16, the test results are almost the same as the blurred ones, is it just because of the changed channel-rate? Could you show your result?

**Comment by dyfloveslife** [comment]
Hi, Have you run successfully? Why do I have a mistake?
```
OSError: Unable to open file (unable to open file: name = 'data/data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
Can you tell me how to solve it? Thanks a lot!

**Comment by leftthomas** [comment]
@dyfloveslife 
Duplicate of #13

**Comment by leftthomas** [comment]
@Alukassh 
Duplicate of #23
