### ISSUE TITLE
why the d_loss tends to be zero and how to express the adversarial loss  as the paper said

### ISSUE THREAD

**Issue by Alukassh** [leftthomas/ImageDeblurring#30]
Sorry to bother you. 
When trained for a few epoch, the d_loss tends to be zero, does that means the generator has been trained well enough or  there are something wrong with the discriminator loss expressions?
Another question is, how to express the adversarial loss  as the paper said? someone has any ideas ？

**Comment by leftthomas** [comment]
@Alukassh This is not the problem about the code, you could discuss these with others on `reddit`
