### ISSUE TITLE
`pydot` failed to call GraphViz.

### ISSUE THREAD

**Issue by dyfloveslife** [leftthomas/ImageDeblurring#31]
Hello, when I run `model.py`, I get the following error:
```
OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.
```
I used  `pip3 install graphviz`，but it still doesn't work.
Have you encountered this situation?

**Comment by leftthomas** [comment]
@dyfloveslife `graphviz ` is not installed by `pip`, please visit [Graphviz](http://www.graphviz.org) to see how to install it.

**Comment by dyfloveslife** [comment]
Thank you very much for your reply, it has been solved, thank you！：）
