### ISSUE TITLE
what is "Channel Rate" referring to...?

### ISSUE THREAD

**Issue by hulidv** [leftthomas/ImageDeblurring#33]
Hi Thanks very much for sharing the algorithm. Could you help to share what is "channel rate" referring to? I can't find it in the paper you've shared. 

For my case, the generator_loss keeps high ranging from 2000-7000. Do you think changing the channel rate could help? It seems i have vanishing gradient issue here. 

Thanks

**Comment by leftthomas** [comment]
#23 ,the paper has `channel rate`, make sure you have read the paper carefully.
