### ISSUE TITLE
resoureceExhaustedError:

### ISSUE THREAD

**Issue by drikchen** [leftthomas/ImageDeblurring#5]
OOM when allocating tensor with shape[2,256,256,640]
when I run train.py , this error always happen

**Comment by leftthomas** [comment]
@drikchen #1 #3

**Comment by drikchen** [comment]
thanks for your reply, I saw #1 #3  and I change the channel rate to 32 , my batch size is 2, then I run the code successfully. However, the result is not okay .  Epoch is 10, when it runs the 9th epoch, the generated image is blurry but the color is okay .  The color is not okay when it runs the last epoch. I am very confused. Can I ask if you get the satisfactory result with this code and do you know how I run a good result?
