### ISSUE TITLE
AssertionError: AbstractConv shape mismatch: shape of image does not match given imshp.

### ISSUE THREAD

**Issue by dm0288** [leftthomas/ImageDeblurring#6]
Hi,
While running the main.py script I am getting error along with warnings as follows:

Using Theano backend.
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_1 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_2 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_3 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_4 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_5 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_6 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_7 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_8 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_9 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_10 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_11 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_12 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_13 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_14 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_15 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer lambda_16 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 256, 256, 3)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
('epoch: ', 1, '/', 10)
('batches: ', 302)
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    train(batch_size=2, epoch_num=10)
  File "main.py", line 51, in train
    d_loss = d.train_on_batch(x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1839, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1224, in __call__
    return self.function(*inputs)
  File "/home/env114/Desktop/Imges/deeplearning/Theano/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/env114/Desktop/Imges/deeplearning/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/env114/Desktop/Imges/deeplearning/Theano/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
AssertionError: AbstractConv shape mismatch: shape of image does not match given imshp.
Apply node that caused the error: Assert{msg='AbstractConv shape mismatch: shape of image does not match given imshp.'}(InplaceDimShuffle{0,3,1,2}.0, Elemwise{eq,no_inplace}.0, Elemwise{Composite{EQ(Switch(LT(i0, i1), i0, i1), i2)}}.0, Elemwise{Composite{EQ(Switch(LT(i0, i1), i0, i1), i2)}}.0)
Toposort index: 179
Inputs types: [TensorType(float32, 4D), TensorType(bool, scalar), TensorType(bool, scalar), TensorType(bool, scalar)]
Inputs shapes: [(4, 3, 64, 64), (), (), ()]
Inputs strides: [(786432, 4, 3072, 12), (), (), ()]
Inputs values: ['not shown', array(True), array(False), array(False)]
Outputs clients: [[Assert{msg='AbstractConv_gradWeights shape mismatch: shape of image does not match given imshp.'}(Assert{msg='AbstractConv shape mismatch: shape of image does not match given imshp.'}.0, Elemwise{eq,no_inplace}.0, Elemwise{Composite{EQ(Switch(LT(i0, i1), i0, i1), i2)}}.0, Elemwise{Composite{EQ(Switch(LT(i0, i1), i0, i1), i2)}}.0), CorrMM{half, (2, 2), (1, 1)}(Assert{msg='AbstractConv shape mismatch: shape of image does not match given imshp.'}.0, Subtensor{::, ::, ::int64, ::int64}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "main.py", line 104, in <module>
    train(batch_size=2, epoch_num=10)
  File "main.py", line 17, in train
    d = discriminator_model()
  File "/home/env114/Downloads/ImageDeblurring-master/model.py", line 120, in discriminator_model
    x = [model(patch) for patch in list_patch]
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2061, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2212, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1913, in conv2d
    filter_dilation=dilation_rate)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Why I am getting this error and How can I fix this?

**Comment by leftthomas** [comment]
@dm02 you should use tensorflow as backend
